<a href="https://colab.research.google.com/github/be1le/machine-learning/blob/basic/%EB%94%A5%EB%9F%AC%EB%8B%9D_XOR.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import Adam, SGD

# XOR 데이터셋

![](https://i.imgur.com/llFchxI.png)

In [ ]:
x_data = np.array([[0, 0], [0, 1], [1, 0], [1, 1]], dtype=np.float32)
y_data = np.array([[0], [1], [1], [0]], dtype=np.float32)

# XOR 이진 논리 회귀

In [ ]:
model = Sequential([
  Dense(1, activation='sigmoid')
])

model.compile(loss='binary_crossentropy', optimizer=SGD(lr=0.1))

model.fit(x_data, y_data, epochs=1000, verbose=0) # Verbose = 0 출력하지말아라 verbose=1 출력해라 

/usr/local/lib/python3.7/dist-packages/keras/optimizer_v2/gradient_descent.py:102: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  super(SGD, self).__init__(name, **kwargs)


In [ ]:
y_pred = model.predict(x_data)

print(y_pred)

[[0.49640813]
 [0.4992991 ]
 [0.49957353]
 [0.50246453]]


# XOR 딥러닝(MLP)

In [ ]:
model = Sequential([ # 순차적으로 레이어를 쌓는 건데 실무에서는 사실 이용하기가 어렵다. 
  Dense(8, activation='relu'),#히든레이어  활성화함수는 relu
  Dense(1, activation='sigmoid'), #출력이하나짜리라서 dense =1 
])

model.compile(loss='binary_crossentropy', optimizer=Adam(lr=0.1))

model.fit(x_data, y_data, epochs=1000, verbose=0)

/usr/local/lib/python3.7/dist-packages/keras/optimizer_v2/adam.py:105: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  super(Adam, self).__init__(name, **kwargs)


In [ ]:
y_pred = model.predict(x_data)

print(y_pred)

[[4.3645501e-04]
 [9.9994743e-01]
 [9.9994409e-01]
 [4.4764747e-05]]


# Keras Functional API

우리는 지금까지 Keras의 Sequential 클래스를 사용하여 Sequential API를 사용했습니다. Sequential API는 순차적인 모델 설계에는 편리한 API 이지만, 복잡한 네트워크를 설계하기에는 한계가 있기 때문에 실무에서는 Functional API를 주로 사용합니다.

위에서 했던 XOR 딥러닝 문제를 Functional API로 다시 작성해보겠습니다!

In [ ]:
import numpy as np
from tensorflow.keras.models import Sequential, Model # 시퀀셜대신에 모델을 쓸거고
from tensorflow.keras.layers import Dense, Input # 댄스레이어 뿐만아니라 인풋레이어 까지 불러와줘야한다. 
from tensorflow.keras.optimizers import Adam, SGD

`model.summary()` 를 사용하여 모델의 구조를 확인할 수 있습니다.

Sequential API를 사용하면 구조를 확인하기 힘들지만 Functional API를 사용하면 `model.summary()`를 사용하여 구조를 확인하기 쉽다는 장점도 있습니다.

In [ ]:
input = Input(shape=(2,)) #인풋레이어의 크기를 지정해준다. 인풋노드가 2개가 된다! 
hidden = Dense(8, activation='relu')(input) #시퀀셜레이어와 다른점. 히든을 인풋에 넣어줘야하는거! 댄스가다시 히든에들어간다. 
output = Dense(1, activation='sigmoid')(hidden) #히든레이어를 다음거에 다시넣어준다. 

model = Model(inputs=input, outputs=output) #시퀀셜대신 모델을 사용한다. inputs,outputs복수형으로 적기 

model.compile(loss='binary_crossentropy', optimizer=Adam(lr=0.1))

model.summary() # 모델의 개요를 볼수있다. 

Model: "model_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_2 (InputLayer)        [(None, 2)]               0         
                                                                 
 dense_5 (Dense)             (None, 8)                 24        
                                                                 
 dense_6 (Dense)             (None, 1)                 9         
                                                                 
Total params: 33
Trainable params: 33
Non-trainable params: 0
_________________________________________________________________


/usr/local/lib/python3.7/dist-packages/keras/optimizer_v2/adam.py:105: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  super(Adam, self).__init__(name, **kwargs)


In [ ]:
model.fit(x_data, y_data, epochs=1000, verbose=0)

y_pred = model.predict(x_data)

print(y_pred)

[[6.465614e-04]
 [9.999424e-01]
 [9.999398e-01]
 [4.562672e-05]]
